name: .NET Coverage

on:
  push:
    branches:
      - dev

  pull_request:

jobs:
  coverage:
    uses: ./.github/workflows/dotnet-ci-generic.yml
    with:
      os: 'ubuntu-latest'
      coverage: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
